# Generated by Django 6.0.4 on 2026-04-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_alter_scanurl_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanreport',
            options={'ordering': ['-id']},
        ),
    ]
